import React from 'react';

const BringReceiptsSection: React.FC = () => {
  return (
    <div className="relative content-start items-start box-border caret-transparent gap-x-0 flex basis-auto flex-col grow-0 shrink-0 h-min justify-center gap-y-0 w-full overflow-clip md:basis-0 md:grow md:h-[560px] md:w-px after:accent-auto after:box-border after:caret-transparent after:text-black after:block after:text-xs after:not-italic after:normal-nums after:font-normal after:h-full after:tracking-[normal] after:leading-[normal] after:list-outside after:list-disc after:absolute after:text-start after:indent-[0px] after:normal-case after:visible after:w-full after:border-zinc-800 after:border-b after:border-separate after:border-solid after:left-0 after:top-0 after:font-sans_serif">
      <div className="relative content-start items-start box-border caret-transparent gap-x-2 flex flex-col shrink-0 h-min justify-start gap-y-2 w-full pt-10 pb-6 px-0 md:px-8">
        <div className="box-content caret-black block md:aspect-auto md:box-border md:caret-transparent md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static box-content caret-black block flex-row shrink justify-normal min-h-0 min-w-0 w-auto break-normal md:relative md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:shrink-0 md:justify-start md:min-h-[auto] md:min-w-[auto] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <h2 className="text-black text-2xl font-bold box-content caret-black tracking-[normal] leading-[normal] min-h-0 min-w-0 text-start break-normal font-times md:text-white md:text-[32px] md:aspect-auto md:box-border md:caret-transparent md:tracking-[-0.32px] md:leading-10 md:min-h-[auto] md:min-w-[auto] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-inter">Bring Receipts</h2>
          </div>
        </div>
        <div className="box-content caret-black block md:aspect-auto md:box-border md:caret-transparent md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static box-content caret-black block flex-row shrink justify-normal max-w-none min-h-0 min-w-0 w-auto break-normal md:relative md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:shrink-0 md:justify-start md:max-w-[480px] md:min-h-[auto] md:min-w-[auto] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <p className="text-black text-base font-normal box-content caret-black tracking-[normal] leading-[normal] min-h-0 min-w-0 break-normal font-times md:text-neutral-300 md:text-sm md:font-medium md:aspect-auto md:box-border md:caret-transparent md:tracking-[0.14px] md:leading-[22px] md:min-h-[auto] md:min-w-[auto] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-inter">
              Score games, record highlights, and give props where it's due.
              <br className="md:aspect-auto md:box-border md:caret-transparent md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
              Track wins, MVPs, and clutch moments across every game you play.
            </p>
          </div>
        </div>
      </div>
      <div className="relative box-border caret-transparent basis-auto grow-0 shrink-0 h-[400px] w-full overflow-clip md:basis-0 md:grow md:h-px">
        <div className="box-content caret-black block md:aspect-auto md:box-border md:caret-transparent md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static box-content caret-black shrink transform-none left-auto top-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[-50.0%] md:translate-y-[-50.0%] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-2/4 md:top-2/4">
            <div className="static box-content caret-black h-auto w-auto md:relative md:aspect-auto md:box-border md:caret-transparent md:h-[416px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[432px] md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <div className="static box-content caret-black gap-x-[normal] shrink h-auto gap-y-[normal] w-auto left-auto top-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:gap-x-0 md:shrink-0 md:h-[368px] md:left-[calc(50%_-_184px)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-0 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:top-[calc(50%_-_184px)] md:w-[368px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="static box-content caret-black shrink h-auto opacity-100 w-auto rounded-none left-auto top-auto md:[mask-image:linear-gradient(0deg,rgba(0,0,0,0)_0%,rgb(0,0,0)_100%)] md:absolute md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:h-[264px] md:left-[calc(50%_-_132px)] md:opacity-[0.04] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:top-[calc(50%_-_132px)] md:w-[264px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[100%] after:md:accent-auto after:md:box-border after:md:caret-transparent after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:border-gray-200 after:md:rounded-[100%] after:md:border-separate after:md:border-solid after:md:left-0 after:md:top-0 after:md:font-sans_serif"></div>
                <div className="static box-content caret-black shrink h-auto opacity-100 w-auto rounded-none left-auto top-auto md:[mask-image:linear-gradient(0deg,rgba(0,0,0,0)_0%,rgb(0,0,0)_100%)] md:absolute md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:h-[368px] md:left-[calc(50%_-_184px)] md:opacity-[0.0025] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:top-[calc(50%_-_184px)] md:w-[368px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[100%] after:md:accent-auto after:md:box-border after:md:caret-transparent after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:border-gray-200 after:md:rounded-[100%] after:md:border-separate after:md:border-solid after:md:left-0 after:md:top-0 after:md:font-sans_serif"></div>
                <div className="static [align-items:normal] box-content caret-black gap-x-[normal] block flex-row shrink h-auto justify-normal gap-y-[normal] w-auto left-auto top-auto md:[mask-image:linear-gradient(270deg,rgba(0,0,0,0)_0.32904%,rgb(0,0,0)_12.8502%,rgb(0,0,0)_86.3053%,rgba(0,0,0,0)_100%)] md:absolute md:content-center md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2 md:flex md:flex-col md:shrink-0 md:h-[201px] md:justify-center md:left-[calc(50%_-_94.5px)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:top-[calc(48.913%_-_100.5px)] md:w-[189px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <div className="static box-content caret-black shrink h-auto min-h-0 min-w-0 rounded-none md:relative md:aspect-[0.731343_/_1] md:box-border md:caret-transparent md:shrink-0 md:h-full md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl">
                    <div className="static box-content caret-black rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl md:inset-0">
                      <img src="https://c.animaapp.com/mevoah3qcxP2EM/assets/Kx5aHFWxG9ccn5Rm3myPyE9RI.png" alt="" className="box-content caret-black h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_220_/_302] md:box-border md:caret-transparent md:h-full md:object-contain md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-xl" />
                    </div>
                    <div className="static bg-none box-content caret-black shrink h-auto opacity-100 transform-none w-auto rounded-none left-auto top-auto md:absolute md:aspect-auto md:bg-[radial-gradient(50%_50%,rgb(255,255,255)_0%,rgba(255,255,255,0)_100%)] md:box-border md:caret-transparent md:shrink-0 md:h-[168px] md:left-[calc(-55.102%_-_32px)] md:opacity-20 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:top-[calc(44.7761%_-_84px)] md:rotate-[8.999976735956185deg] md:w-16 md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"></div>
                  </div>
                </div>
                <div className="static shadow-none box-content caret-black gap-x-[normal] shrink gap-y-[normal] w-auto rounded-none right-auto top-auto md:absolute md:aspect-square md:shadow-[rgba(0,0,0,0.1)_0px_0px_25.6px_0px] md:box-border md:caret-transparent md:gap-x-0 md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:gap-y-0 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6 md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[44.8px] md:right-[95px] md:top-[46px]">
                  <div className="static box-content caret-black rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[44.8px] md:inset-0">
                    <img src="https://c.animaapp.com/mevoah3qcxP2EM/assets/TNrIeUZkXdpALtmCGXgVvGoDy24.png" alt="" className="box-content caret-black h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_160_/_160] md:box-border md:caret-transparent md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[44.8px]" />
                  </div>
                </div>
                <div className="static box-content caret-black gap-x-[normal] shrink gap-y-[normal] w-auto rounded-none left-auto top-auto md:absolute md:aspect-square md:box-border md:caret-transparent md:gap-x-0 md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:gap-y-0 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6 md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[38.4px] md:left-[213px] md:top-[27px] after:md:accent-auto after:md:box-border after:md:caret-transparent after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:rounded-[38.4px] after:md:border-separate after:md:border-solid after:md:border-white/10 after:md:left-0 after:md:top-0 after:md:font-sans_serif">
                  <div className="static box-content caret-black rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[38.4px] md:inset-0">
                    <img src="https://c.animaapp.com/mevoah3qcxP2EM/assets/LeWoIqQ7qzBe2GD7GG281RYzxk.png" alt="" className="box-content caret-black h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_160_/_161] md:box-border md:caret-transparent md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[38.4px]" />
                  </div>
                </div>
                <div className="static shadow-none box-content caret-black gap-x-[normal] shrink gap-y-[normal] transform-none w-auto rounded-none left-auto top-auto md:absolute md:aspect-square md:shadow-[rgba(0,0,0,0.1)_0px_0px_25.6px_0px] md:box-border md:caret-transparent md:gap-x-0 md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:gap-y-0 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[-50.0%] md:w-6 md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[44.8px] md:left-2/4 md:top-5">
                  <div className="static box-content caret-black rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[44.8px] md:inset-0">
                    <img src="https://c.animaapp.com/mevoah3qcxP2EM/assets/dDnqkzQfB3pmvEdrFSxAJSkAyyk.png" alt="" className="box-content caret-black h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_500_/_500] md:box-border md:caret-transparent md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[44.8px]" />
                  </div>
                </div>
                <div className="static box-content caret-black gap-x-[normal] shrink gap-y-[normal] w-auto rounded-none left-auto top-auto md:absolute md:aspect-square md:box-border md:caret-transparent md:gap-x-0 md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:gap-y-0 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6 md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[38.4px] md:left-[131px] md:top-[27px] after:md:accent-auto after:md:box-border after:md:caret-transparent after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:rounded-[38.4px] after:md:border-separate after:md:border-solid after:md:border-white/10 after:md:left-0 after:md:top-0 after:md:font-sans_serif">
                  <div className="static box-content caret-black rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[38.4px] md:inset-0">
                    <img src="https://c.animaapp.com/mevoah3qcxP2EM/assets/31DVpHa0tDScDFuv7JLYSclSvhA.png" alt="" className="box-content caret-black h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_160_/_161] md:box-border md:caret-transparent md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[38.4px]" />
                  </div>
                </div>
                <div className="static box-content caret-black gap-x-[normal] shrink gap-y-[normal] w-auto rounded-none left-auto top-auto md:absolute md:aspect-square md:box-border md:caret-transparent md:gap-x-0 md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:gap-y-0 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6 md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[38.4px] md:left-[95px] md:top-[46px] after:md:accent-auto after:md:box-border after:md:caret-transparent after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:rounded-[38.4px] after:md:border-separate after:md:border-solid after:md:border-white/10 after:md:left-0 after:md:top-0 after:md:font-sans_serif">
                  <div className="static box-content caret-black rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[38.4px] md:inset-0">
                    <img src="https://c.animaapp.com/mevoah3qcxP2EM/assets/izD3uE80P8HErXrNyyIoCER5X7A.png" alt="" className="box-content caret-black h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_160_/_160] md:box-border md:caret-transparent md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[38.4px]" />
                  </div>
                </div>
              </div>
              <div className="static box-content caret-black shrink h-auto mix-blend-normal transform-none w-auto z-auto left-auto top-auto md:[mask-image:radial-gradient(50%_50%,rgb(0,0,0)_0%,rgba(0,0,0,0)_71.9419%)] md:absolute md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:h-[200px] md:left-[calc(37.037%_-_100px)] md:mix-blend-screen md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:top-[calc(51.9231%_-_100px)] md:rotate-45 md:w-[200px] md:z-0 md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="static box-content caret-black shrink top-auto inset-x-auto md:absolute md:aspect-square md:box-border md:caret-transparent md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:top-0 md:inset-x-0">
                  <video src="https://framerusercontent.com/assets/HnYBrF0tS5gvFwodwB76VpriQk.mp4" loop preload="auto" playsInline autoPlay className="box-content caret-black h-auto object-contain align-middle w-auto md:aspect-auto md:box-border md:caret-transparent md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></video>
                </div>
              </div>
              <div className="static box-content caret-black shrink h-auto mix-blend-normal transform-none w-auto z-auto left-auto top-auto md:[mask-image:radial-gradient(50%_50%,rgb(0,0,0)_0%,rgba(0,0,0,0)_71.9419%)] md:absolute md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:h-[200px] md:left-[calc(29.6296%_-_100px)] md:mix-blend-screen md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:top-[calc(53.8462%_-_100px)] md:rotate-45 md:w-[200px] md:z-0 md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="static box-content caret-black shrink top-auto inset-x-auto md:absolute md:aspect-square md:box-border md:caret-transparent md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:top-0 md:inset-x-0">
                  <video src="https://framerusercontent.com/assets/HnYBrF0tS5gvFwodwB76VpriQk.mp4" loop preload="auto" playsInline autoPlay className="box-content caret-black h-auto object-contain align-middle w-auto md:aspect-auto md:box-border md:caret-transparent md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></video>
                </div>
              </div>
              <div className="static box-content caret-black shrink h-auto mix-blend-normal transform-none w-auto z-auto left-auto top-auto md:[mask-image:radial-gradient(50%_50%,rgb(0,0,0)_0%,rgba(0,0,0,0)_71.9419%)] md:absolute md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:h-[200px] md:left-[calc(62.963%_-_100px)] md:mix-blend-soft-light md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:top-[calc(38.4615%_-_100px)] md:rotate-45 md:w-[200px] md:z-0 md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                <div className="static box-content caret-black shrink top-auto inset-x-auto md:absolute md:aspect-square md:box-border md:caret-transparent md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:top-0 md:inset-x-0">
                  <video src="https://framerusercontent.com/assets/HnYBrF0tS5gvFwodwB76VpriQk.mp4" loop preload="metadata" playsInline className="box-content caret-black h-auto object-contain align-middle w-auto md:aspect-auto md:box-border md:caret-transparent md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></video>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BringReceiptsSection;
