import React from 'react';
import JoinWaitlistButton from '../ui/JoinWaitlistButton';

const HeroSection: React.FC = () => {
  return (
    <section className="relative content-center items-center box-border caret-transparent gap-x-2.5 flex flex-col shrink-0 h-min justify-end min-h-[1000px] gap-y-2.5 w-full overflow-hidden pt-[120px] pb-8 md:pt-8">
      <div className="absolute box-border caret-transparent shrink-0 z-[1] inset-0">
        <div className="relative box-border caret-transparent gap-x-2.5 h-full gap-y-2.5 w-full overflow-clip"></div>
      </div>
      <div className="box-content caret-black block md:aspect-auto md:box-border md:caret-transparent md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static box-content caret-black shrink transform-none w-auto z-auto left-auto top-auto md:absolute md:aspect-[0.456662_/_1] md:box-border md:caret-transparent md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[-50.0%] md:translate-y-[-50.0%] md:w-60 md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-2/4 md:top-[44%]">
          <div className="static box-content caret-black h-auto w-auto md:relative md:aspect-auto md:box-border md:caret-transparent md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <div className="static box-content caret-black shrink rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[40px] md:inset-0">
              <div className="static box-content caret-black rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[40px] md:inset-0">
                <img sizes="240px" src="https://c.animaapp.com/mevoah3qcxP2EM/assets/ANT40OZX49LGPJcKMWoBeYiZmCU.png" alt="" className="box-content caret-black h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_359_/_784] md:box-border md:caret-transparent md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[40px]" />
              </div>
            </div>
            <div className="static box-content caret-black shrink transform-none w-auto left-auto top-auto md:[mask-image:linear-gradient(0deg,rgba(0,0,0,0)_6%,rgb(0,0,0)_33%)] md:absolute md:aspect-[0.641667_/_1] md:box-border md:caret-transparent md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[-50.0%] md:translate-y-[-50.0%] md:w-[217%] md:overflow-clip md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-[33%] md:top-[76%]">
              <div className="static box-content caret-black inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
                <img sizes="calc(240px * 2.17)" src="https://c.animaapp.com/mevoah3qcxP2EM/assets/bnIpi7skfKLrvJwY5GI6c9d2iY.png" alt="" className="box-content caret-black h-auto object-fill align-middle w-auto md:aspect-[auto_771_/_1200] md:box-border md:caret-transparent md:h-full md:object-contain md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="absolute bg-[linear-gradient(rgba(13,13,13,0)_0%,rgb(13,13,13)_100%)] box-border caret-transparent gap-x-2.5 shrink-0 h-1/4 gap-y-2.5 z-[1] overflow-clip bottom-0 inset-x-0"></div>
      <div className="relative content-start items-start box-border caret-transparent gap-x-6 flex flex-col shrink-0 h-min justify-center max-w-[440px] gap-y-6 w-full z-[2] px-5 md:content-end md:items-end md:flex-row md:max-w-screen-xl md:px-7">
        <div className="relative content-start items-start box-border caret-transparent gap-x-2.5 flex basis-auto flex-col grow-0 shrink-0 h-min justify-center gap-y-2.5 w-full md:basis-0 md:grow md:w-px">
          <div className="box-content caret-black block md:aspect-auto md:box-border md:caret-transparent md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <div className="static box-content caret-black block flex-row shrink justify-normal max-w-none min-h-0 min-w-0 w-auto break-normal md:relative md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:shrink-0 md:justify-start md:max-w-[520px] md:min-h-[auto] md:min-w-[auto] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <h1 className="text-black text-[32px] box-content caret-black leading-[normal] min-h-0 min-w-0 normal-case break-normal font-times md:text-stone-50 md:text-[200px] md:aspect-auto md:box-border md:caret-transparent md:leading-[164px] md:min-h-[auto] md:min-w-[auto] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:uppercase md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-coign_pro_27_bold">
                <span className="box-content caret-black text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">T</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">h</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">e</span>
                </span>
                <span className="box-content caret-black text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">N</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">e</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">w</span>
                </span>
                <span className="box-content caret-black text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></span>
                <br className="md:aspect-auto md:box-border md:caret-transparent md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
                <span className="box-content caret-black text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">P</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">l</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">a</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">y</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">g</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">r</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">o</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">u</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">n</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">d</span>
                </span>
                <span className="box-content caret-black text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">f</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">o</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">r</span>
                </span>
                <span className="box-content caret-black text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">p</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">i</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">c</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">k</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">u</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">p</span>
                </span>
                <span className="box-content caret-black text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">B</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">a</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">s</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">k</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">e</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">t</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">b</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">a</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">l</span>
                  <span className="box-content caret-black inline text-wrap break-normal md:aspect-auto md:box-border md:caret-transparent md:inline-block md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">l</span>
                </span>
              </h1>
            </div>
          </div>
        </div>
        <div className="relative content-start items-start box-border caret-transparent gap-x-5 flex basis-auto flex-col grow-0 shrink-0 h-min justify-center max-w-[480px] gap-y-5 w-full md:basis-0 md:grow md:w-px">
          <div className="relative content-start items-start box-border caret-transparent gap-x-3 flex flex-col shrink-0 h-min justify-start gap-y-3 w-full">
            <div className="relative box-border caret-transparent flex flex-col shrink-0 justify-start break-words w-full">
              <p className="text-neutral-400 font-bold box-border caret-transparent tracking-[0.36px] leading-[18px] break-words uppercase font-inter">Join the waitlist</p>
            </div>
            <div className="relative box-border caret-transparent flex flex-col shrink-0 justify-start break-words w-full">
              <p className="text-neutral-300 text-lg font-medium box-border caret-transparent tracking-[0.18px] leading-7 break-words font-inter">Find games. Track stats. Build your crew. The ultimate playground for hoopers—pickup just got organized.</p>
            </div>
          </div>
          <div className="relative box-border caret-transparent shrink-0">
            <a href="./#join-waitlist" className="relative text-blue-700 content-center items-center box-border caret-transparent gap-x-1 flex h-11 justify-center gap-y-1 w-min overflow-clip px-[22px] py-3 rounded-[14px]">
              <div className="absolute content-center items-center box-border caret-transparent gap-x-0 flex flex-col shrink-0 justify-start gap-y-0 z-0 overflow-clip inset-0">
                <div className="relative bg-white box-border caret-transparent gap-x-1 shrink-0 h-full gap-y-1 w-full z-0"></div>
                <div className="relative bg-zinc-800 box-border caret-transparent gap-x-1 shrink-0 h-full gap-y-1 w-full z-0"></div>
              </div>
              <div className="relative box-border caret-transparent flex flex-col shrink-0 justify-start text-nowrap">
                <p className="text-stone-950 text-sm font-semibold box-border caret-transparent leading-5 text-nowrap font-inter">Join waitlist</p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
