import React from 'react';
import { clubsData } from '../../data/clubsData';
import ClubCard from '../ui/ClubCard';

const HoopSquadsSection: React.FC = () => {
  return (
    <div className="relative content-center items-center box-border caret-transparent gap-x-0 flex flex-col shrink-0 h-min justify-center gap-y-0 w-full overflow-clip md:flex-row">
      <div className="relative content-start items-start box-border caret-transparent gap-x-0 flex basis-auto flex-col grow-0 shrink-0 h-min justify-center gap-y-0 w-full overflow-clip md:basis-0 md:grow md:h-[560px] md:w-px after:accent-auto after:box-border after:caret-transparent after:text-black after:block after:text-xs after:not-italic after:normal-nums after:font-normal after:h-full after:tracking-[normal] after:leading-[normal] after:list-outside after:list-disc after:absolute after:text-start after:indent-[0px] after:normal-case after:visible after:w-full after:border-zinc-800 after:border-r-0 after:border-b after:border-separate after:border-solid after:left-0 after:top-0 after:font-sans_serif after:md:border-b-0 after:md:border-r">
        <div className="relative content-start items-start box-border caret-transparent gap-x-2 flex flex-col shrink-0 h-min justify-start gap-y-2 w-full pt-10 pb-6 px-0 md:px-8">
          <div className="box-content caret-black block md:aspect-auto md:box-border md:caret-transparent md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <div className="static box-content caret-black block flex-row shrink justify-normal min-h-0 min-w-0 w-auto break-normal md:relative md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:shrink-0 md:justify-start md:min-h-[auto] md:min-w-[auto] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <h2 className="text-black text-2xl font-bold box-content caret-black tracking-[normal] leading-[normal] min-h-0 min-w-0 text-start break-normal font-times md:text-white md:text-[32px] md:aspect-auto md:box-border md:caret-transparent md:tracking-[-0.32px] md:leading-10 md:min-h-[auto] md:min-w-[auto] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-inter">Hoop Squads, Organized</h2>
            </div>
          </div>
          <div className="relative box-border caret-transparent flex flex-col shrink-0 justify-start max-w-[480px] break-words w-full">
            <p className="text-neutral-300 text-sm font-medium box-border caret-transparent tracking-[0.14px] leading-[22px] break-words font-inter">Join or create clubs with your crew. Share content, schedule private runs, and build something bigger than just a game.</p>
          </div>
        </div>
        <div className="relative box-border caret-transparent basis-auto grow-0 shrink-0 h-[340px] w-full overflow-clip md:basis-0 md:grow md:h-px">
          <div className="absolute box-border caret-transparent shrink-0 overflow-clip inset-0">
            <div className="box-content caret-black block md:aspect-auto md:box-border md:caret-transparent md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <div className="static box-content caret-black shrink transform-none w-auto left-auto top-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-y-[-50.0%] md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-2/4">
                <div className="static [align-items:normal] box-content caret-black gap-x-[normal] block flex-row h-auto justify-normal gap-y-[normal] w-auto px-0 md:[mask-image:linear-gradient(270deg,rgba(0,0,0,0)_0%,rgb(0,0,0)_30%,rgba(0,0,0,0.89)_96%,rgba(0,0,0,0)_100%)] md:relative md:content-start md:items-start md:aspect-auto md:box-border md:caret-transparent md:gap-x-4 md:flex md:flex-col md:h-min md:justify-start md:overscroll-x-auto md:overscroll-y-auto md:gap-y-4 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:overflow-clip md:[mask-position:0%] md:bg-left-top md:px-10 md:scroll-m-0 md:scroll-p-[auto]">
                  <div className="static box-content caret-black block flex-row shrink justify-normal min-h-0 min-w-0 text-wrap md:relative md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:shrink-0 md:justify-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <p className="text-black text-base font-normal box-content caret-black tracking-[normal] leading-[normal] min-h-0 min-w-0 normal-case text-wrap font-times md:text-zinc-600 md:text-[10px] md:font-medium md:aspect-auto md:box-border md:caret-transparent md:tracking-[0.6px] md:leading-[18px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:uppercase md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-inter">ALL CLUBS</p>
                  </div>
                  <div className="static [align-items:normal] box-content caret-black gap-x-[normal] block shrink h-auto justify-normal min-h-0 min-w-0 gap-y-[normal] w-auto md:relative md:content-center md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-2.5 md:flex md:shrink-0 md:h-min md:justify-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2.5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    {clubsData.map((club) => (
                      <ClubCard key={club.id} club={club} />
                    ))}
                  </div>
                  <div className="static box-content caret-black shrink w-auto z-auto right-auto inset-y-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-6/12 md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:right-0 md:inset-y-0">
                    <div className="static box-content caret-black h-auto w-auto md:relative md:aspect-auto md:box-border md:caret-transparent md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <div className="static box-content caret-black z-auto inset-auto md:[mask-image:linear-gradient(to_right,rgba(0,0,0,0)_0%,rgb(0,0,0)_12.5%,rgb(0,0,0)_25%,rgba(0,0,0,0)_37.5%)] md:absolute md:aspect-auto md:backdrop-blur-[0.5px] md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                      <div className="static box-content caret-black z-auto inset-auto md:[mask-image:linear-gradient(to_right,rgba(0,0,0,0)_12.5%,rgb(0,0,0)_25%,rgb(0,0,0)_37.5%,rgba(0,0,0,0)_50%)] md:absolute md:aspect-auto md:backdrop-blur-[0.25px] md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[2] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                      <div className="static box-content caret-black z-auto inset-auto md:[mask-image:linear-gradient(to_right,rgba(0,0,0,0)_25%,rgb(0,0,0)_37.5%,rgb(0,0,0)_50%,rgba(0,0,0,0)_62.5%)] md:absolute md:aspect-auto md:backdrop-blur-[0.5px] md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[3] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                      <div className="static box-content caret-black z-auto inset-auto md:[mask-image:linear-gradient(to_right,rgba(0,0,0,0)_37.5%,rgb(0,0,0)_50%,rgb(0,0,0)_62.5%,rgba(0,0,0,0)_75%)] md:absolute md:aspect-auto md:backdrop-blur-[1px] md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[4] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                      <div className="static box-content caret-black z-auto inset-auto md:[mask-image:linear-gradient(to_right,rgba(0,0,0,0)_50%,rgb(0,0,0)_62.5%,rgb(0,0,0)_75%,rgba(0,0,0,0)_87.5%)] md:absolute md:aspect-auto md:backdrop-blur-[2px] md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[5] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                      <div className="static box-content caret-black z-auto inset-auto md:[mask-image:linear-gradient(to_right,rgba(0,0,0,0)_62.5%,rgb(0,0,0)_75%,rgb(0,0,0)_87.5%,rgba(0,0,0,0)_100%)] md:absolute md:aspect-auto md:backdrop-blur-sm md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[6] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                      <div className="static box-content caret-black z-auto inset-auto md:[mask-image:linear-gradient(to_right,rgba(0,0,0,0)_75%,rgb(0,0,0)_87.5%,rgb(0,0,0)_100%)] md:absolute md:aspect-auto md:backdrop-blur md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[7] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                      <div className="static box-content caret-black z-auto inset-auto md:[mask-image:linear-gradient(to_right,rgba(0,0,0,0)_87.5%,rgb(0,0,0)_100%)] md:absolute md:aspect-auto md:backdrop-blur-lg md:box-border md:caret-transparent md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[8] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="relative content-start items-start box-border caret-transparent gap-x-2 flex flex-col shrink-0 h-min justify-start gap-y-2 w-full px-0 py-6 md:px-8">
        <div className="relative box-border caret-transparent flex flex-col shrink-0 justify-start break-words w-full">
          <p className="text-neutral-400 font-bold box-border caret-transparent tracking-[0.36px] leading-[18px] break-words uppercase font-inter">From local parks to elite circles—this is your team's new home</p>
        </div>
      </div>
    </div>
  );
};

export default HoopSquadsSection;
